"""empty message

Revision ID: 84522a22b0c4
Revises: 5b3c9b4b82c3
Create Date: 2019-07-20 20:57:28.694385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84522a22b0c4'
down_revision = '5b3c9b4b82c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lunchboxes', sa.Column('archived', sa.Boolean(), nullable=False))
    op.drop_column('lunchboxes', 'available')
    op.add_column('products', sa.Column('archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'archived')
    op.add_column('lunchboxes', sa.Column('available', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('lunchboxes', 'archived')
    # ### end Alembic commands ###
