"""empty message

Revision ID: 9b04d647456d
Revises: 84522a22b0c4
Create Date: 2019-07-20 21:18:33.131920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b04d647456d'
down_revision = '84522a22b0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lunchboxes', sa.Column('locked', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('locked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'locked')
    op.drop_column('lunchboxes', 'locked')
    # ### end Alembic commands ###
