config:
  timeslots:
    deadzone: 30m
  client:
    maxOrders: 2
    maxOrderItems: 1
    cancelOrderTime: 30m
schedule:
  monday:
    start: 9am
    end: 9pm
  tuesday:
    start: 9am
    end: 9pm
  wednesday:
    start: 9am
    end: 9pm
  thursday:
    start: 9am
    end: 9pm
  friday:
    start: 9am
    end: 9pm